# ============================================================================
# SauceDemo Environment Configuration
# Test Automation Framework
# ============================================================================

# Browser Configuration
browser: chromium
headless: true
timeout: 30000
retries: 2

# Application URLs
baseURL: https://www.saucedemo.com
apiBaseURL: https://www.saucedemo.com/api

# Logging Configuration
logging:
  level: info
  format: simple
  transports:
    - console
    - file
  filename: logs/test-saucedemo.log

# Media Capture Configuration
media:
  screenshot:
    mode: only-on-failure
    fullPage: true
  video:
    mode: retain-on-failure
    size:
      width: 1920
      height: 1080

# Performance Monitoring
performance:
  monitoring: true
  metrics:
    - memory
    - network
    - pageLoad
  thresholds:
    pageLoadTime: 5000
    memoryUsage: 100000000
    networkLatency: 1000

# API Mocking Configuration
mocking:
  enabled: false
  routes: []
  responses: {}

# Test Data Configuration
testData:
  seedOnStartup: false
  cleanupOnTeardown: false
  useRealData: true

# Security Configuration
security:
  encryption:
    algorithm: aes-256-gcm
    keyDerivation: pbkdf2
  credentials:
    encryptInMemory: false
    rotateTokens: false

# Feature Flags
features:
  apiTesting: false
  performanceTesting: true
  visualTesting: false
  accessibilityTesting: false
  crossBrowserTesting: true
  mobileTesting: false
  apiMocking: false
  parallelExecution: true

# Retry Configuration
retry:
  maxAttempts: 3
  backoffStrategy: exponential
  initialDelay: 1000
  maxDelay: 10000
  retryableErrors:
    - NETWORK_ERROR
    - TIMEOUT_ERROR
    - PAGE_LOAD_TIMEOUT
    - ELEMENT_NOT_FOUND

# Parallel Execution
parallel:
  enabled: true
  maxWorkers: 2
  shardTests: false
  testIsolation: true
  sharedState: false

# Debug Configuration
debug:
  enabled: false
  breakpoints: false
  stepThrough: false
  saveHar: false
  saveTrace: true
  screenshotOnStep: false

# SauceDemo Specific Settings
saucedemo:
  users:
    standard: standard_user
    locked: locked_out_user
    problem: problem_user
    performance: performance_glitch_user
    error: error_user
    visual: visual_user
  password: secret_sauce
  products:
    backpack: "Sauce Labs Backpack"
    bikeLight: "Sauce Labs Bike Light"
    boltTShirt: "Sauce Labs Bolt T-Shirt"
    fleeceJacket: "Sauce Labs Fleece Jacket"
    onesie: "Sauce Labs Onesie"
    redTShirt: "Test.allTheThings() T-Shirt (Red)"